---

version: '3.9'

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  ci:
    build: .
    depends_on:
      - db
    environment:
      - RAILS_ENV
    command: sh -c "make ci-check"
